### ISSUE TITLE
About input preprocessing

### ISSUE THREAD

**Issue by makinyilmaz** [VCLLab/IFQA#6]
Hi thanks for your amazing work. I wonder what kind of input image preprocessing is required to get meaningful results? For example is there a recommended facial alignment ?

**Comment by SongDoHou** [comment]
Hi, I appreciate with your interest to our work and apologize for late reply.
We set the resolution to 256 x 256. 
Since our model is trained using FFHQ dataset, I recommend utilizing alignment method as FFQH, or this might be helpful: https://github.com/happy-jihye/FFHQ-Alignment (But I never used that before).
